name: poke_list
description: The application aims to list and register pokemons.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0+1
  dio: ^4.0.4
  flutter_mobx: ^2.0.2
  flutter_svg: ^0.23.0+1
  get_it: ^7.2.0
  image_picker: ^0.8.4+4
  infinite_scroll_pagination: ^3.1.0
  mobx: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  mobx_codegen: ^2.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/ash.svg
    - assets/poke_logo.svg
    - assets/poke_ball.svg

  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/RobotoMono-Regular.ttf
          weight: 400
